<?php
// $Id$

/**
 * @file
 * 	Main module file for the autofill module for Nojoshmo
 */

/**
 * Implementation of hook_help() 
 */ 
 
function autofill_help() {
	if ($path == 'admin/help#autofill') {
		return t('Provide autocompletion to Drupal fields');
	}	
} 
 
/**
 * Implementation of hook_init().
 */
 
function autofill_init() {
   global $user;
	 
	 //The path to the mysite module
  $path = drupal_get_path('module', 'autofill');
	
	//Add  the AutoFill plug-in file.
	drupal_add_js($path.'/js/jquery.autofill.js');	
		
	//Add our custom JavaScript file.
	drupal_add_js($path.'/js/autofill.js');	
	
	
}
