<?php
/**
 * @file
 * 	Main module file for the autofill module for Nojoshmo
 */

/**
 * Implementation of hook_help() 
 */ 

function autofill_help() {
  if ($path == 'admin/help#autofill') {
    return t('Provide autocompletion to Drupal fields');
  }
}

/**
 * Implementation of hook_init().
 */
function autofill_init() {
  global $user;
  //The path to the mysite module
  $path = drupal_get_path('module', 'autofill');

  //Add  the AutoFill plug-in file.
  drupal_add_js($path . '/js/jquery.autofill.js');

  //Add our custom JavaScript file.
  drupal_add_js($path . '/js/autofill.js');
}

/**
 * Implementation of hook_perm
 */
function autofill_perm() {
 return array('administer autofill');
}

/**
 * Implementation of hook_menu()
 */
function autofill_menu() {
  $items = array();
  $path = drupal_get_path('module', 'autofill');
   
  $items[$path . '/js/autofill.js'] = array(
    'title' => 'Autofill JS',
    'description' => 'Add id and values to Autofill.',
    'page callback' => 'autofill_js',
    'type' => MENU_CALLBACK,
    'access arguments' => array(true),
  );
  
  $items['admin/settings/autofill'] = array(
    'title' => 'Autofill',
    'description' => 'Configure Autofill.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('autofill_form'),
    'access arguments' => array('administer autofill'),
    'file' => 'autofill.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_form
 */

function autofill_js() {
  $output = ' ';
  $output .= 'Drupal.behaviors.autofill = function(context){ ';
  $default_color = variable_get('autofill_colour_default', '#ccc');
  $active_color = variable_get('autofill_colour_active', '#333');
  $fields = variable_get('autofill_id_field_combos', array());
  foreach ($fields as $delta => $field) {
    $output .= "\n".'$("' . $field['id'] . '").autofill( {
      value: "' . $field['value'] . '",
      prePopulate: "' . $field['pre'] . '",
      defaultTextColor: "' . $default_color . '",
      activeTextColor: "' . $active_color . '",
    });';
  }
  $output .= '}';
  
  header('Content-type: text/javascript;');
  echo $output;
  exit();
}